### ISSUE TITLE
Add Feature: Add ability to install on windows

### ISSUE THREAD

**Issue by Ali-Razmjoo** [Ali-Razmjoo/OWASP-ZSC#12]
Hello friends,

There is a new issue which OWASP ZSC is not able to [install](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/installer.py)/[uninstall](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/uninstaller.py) on `windows `, We would better to solve this earlier.

There are some documents available for users and developers which locate in [here](https://github.com/Ali-Razmjoo/OWASP-ZSC/tree/master/doc) and could be useful!
I'll be so grateful if someone assist me with this issue.

Thank you.

**Comment by timogoosen** [comment]
What exactly is the issue? How are you running it? Are you running it with python in cygwin?

**Comment by Ali-Razmjoo** [comment]
Hi Timo,

There is a [installer file](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/installer.py) which could be use in linux/osx and install the software in same directory `/usr/share/owasp_zsc/` and also [uninstaller file](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/uninstaller.py) which remove the path `/usr/share/owasp-zsc` and also a command line which created by installer file `/usr/share/owasp_zsc/zsc.py`.

Now we've to develop it on windows operation system, it could be install in `C:\somewhere\` and add the `C:\somewhere\` to the environment variables path, then users can run the software via `zsc` command in windows too.

Thank you.
