### ISSUE TITLE
can't install in OS X

### ISSUE THREAD

**Issue by Wingless-Archangel** [Ali-Razmjoo/OWASP-ZSC#2]
Just notice that this project support only Linux based. However, is there any chance that this project will support OS X environment?
```shellscript
❯ sudo python installer.py
Password:
Sorry, This version of software just could be run on linux.
````

**Comment by Ali-Razmjoo** [comment]
thanks for notice, version 1.0.7.1 of this project will be released in couple of days and it will be support on mac osx, and all linux families. and all requiring tools will be removed :)

**Comment by Wingless-Archangel** [comment]
I just cloned from the source. Isn't this one  the latest version?

**Comment by Ali-Razmjoo** [comment]
you cloned version 1.0.7 , version 1.0.7.1 will be release in next 2 days

**Comment by Wingless-Archangel** [comment]
I see. Thank you.
