### ISSUE TITLE
Error :download url 

### ISSUE THREAD

**Issue by jowasp** [Ali-Razmjoo/OWASP-ZSC#22]
I'm trying to use the download option, but I get the following error(list index out of range)
Not sure if I'm using the command correctly

![screenshot 2016-02-14 14 08 47](https://cloud.githubusercontent.com/assets/6704344/13035360/b2a11e04-d324-11e5-83ff-736c5909f737.png)

**Comment by Ali-Razmjoo** [comment]
Hello Johanna,

Thanks for your report, A variable name was missed in new interface in this function, and already fixed.

**Comment by jowasp** [comment]
Seems to work now. Thx
![screenshot 2016-02-15 06 19 15](https://cloud.githubusercontent.com/assets/6704344/13045875/2091673e-d3ac-11e5-8aff-05f13d469057.png)
