### ISSUE TITLE
Remove installer and add list of dependencies

### ISSUE THREAD

**Issue by timogoosen** [Ali-Razmjoo/OWASP-ZSC#27]
I suggest that you don't use an install.py file and just create a list of dependencies with instructions on how to install them. 

Also create instructions on how to install it the way that the install.py file installs it, for if users don't want to run it just as standalone python program. (But assume that most people will just be running it from the directory where it is installed as standlone python program.)

**Comment by Ali-Razmjoo** [comment]
Hi Timo,

There isn't any dependencies for this software, All they need is python, installer file is just copy the files in a path and create the command line to make software able to run in linux/osx terminal, which we need to develop installer for windows #12  too.

Thank you.

**Comment by guangyue** [comment]
now,I know it .Thankyou very much !

2016-02-17 19:13 GMT+08:00 Ali Razmjoo <notifications@github.com>:
