### ISSUE TITLE
Python3 supported

### ISSUE THREAD

**Issue by Wingless-Archangel** [Ali-Razmjoo/OWASP-ZSC#3]
Is there any chance that this project will support python 3?

**Comment by Ali-Razmjoo** [comment]
not yet, i don't got time,  if someone could help to develop on python3, i will glad

**Comment by Wingless-Archangel** [comment]
I'm not that good but I can try.

**Comment by Ali-Razmjoo** [comment]
if you would to help for develop, you may wait some hours , i will release next version sooner, and then you can work on next version for developing, fork,clone and develop, and then send me a pull request, and by the way i glad if you make a user in OWASP community

i will let you know when i update the software in few next hours 
thanks

**Comment by Ali-Razmjoo** [comment]
sorry for delay, software updated.

**Comment by Ali-Razmjoo** [comment]
software updated to be compatible with python3.x and 2.x
