### ISSUE TITLE
control goes to except block and raises attribute error for windll in linux [installer.py]

### ISSUE THREAD

**Issue by Pratik151** [Ali-Razmjoo/OWASP-ZSC#32]
This is small issue which I came across when I tried to install without root permissions.

When running `installer.py` without root permission then it should exit with the message 'Sorry you must run this file as root.' but it is not  and this error is raised : 
```
Traceback (most recent call last):
  File "installer.py", line 48, in <module>
    linux_osx()
  File "installer.py", line 23, in linux_osx
    check_prv()
  File "installer.py", line 20, in check_prv
    if ctypes.windll.shell32.IsUserAnAdmin() != 1:
AttributeError: 'module' object has no attribute 'windll'
```

It is because the `sys.exit()` only raises an exception and it is catched in next except block [here](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/installer.py#L18).

A quick fix would be to catch only `AttributeError`.  I will make PR for this now.

**Comment by Ali-Razmjoo** [comment]
Hello, Thanks for fixing.
PR Merged.
