### ISSUE TITLE
Command-line error 

### ISSUE THREAD

**Issue by b3mb4m** [Ali-Razmjoo/OWASP-ZSC#7]
Yo, just try some test on zsc.Command line seems like buggy,

            root@r00t-VirtualBox:/home/r00t/Desktop# zsc
            Traceback (most recent call last):
            File "/usr/share/owasp_zsc/zsc.py", line 11, in <module>
            from core import run
            File "/usr/share/owasp_zsc/core/run.py", line 25, in <module>
            exec(compile(open('core/commands.py', "rb").read(), 'core/commands.py', 'exec'))
            IOError: [Errno 2] No such file or directory: 'core/commands.py'
            root@r00t-VirtualBox:/home/r00t/Desktop# 

There you go, system informations;
 
           root@r00t-VirtualBox:/home/r00t/Desktop# uname -a
           Linux r00t-VirtualBox 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Good luck my friend :)

**Comment by Ali-Razmjoo** [comment]
Hello,

Thanks for your bug reporting, Please let us know if there are more issues.

Regards.
